version: '2'
services:
#nginx
  nginx:
    image: nginx
    #volumes:
      #コンテンツ部分
      #- "./web:/usr/share/nginx/html"
      #ログディレクトリ
      #- "./dockerfiles/nginx/logs:/Users/yume_yu/docker/nginx/log"
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 172.31.0.2

#python
  api:
    image: python:latest
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.31.0.3

  db:
    image: mariadb
    restart: always
    hostname: 'mariadb'
    ports:
      - "5353:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      app_net:
        ipv4_address: 172.31.0.4

  adminer:
      image: adminer
      restart: always
      depends_on:
        - db
      ports:
        - 8080:8080


networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.31.0.0/24
